backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Статии"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заглавие", name: "title", widget: "string" }
      - { label: "Рубрика", name: "category", widget: "select", options: ["Новини", "Политика", "Свят", "Лайфстайл"] }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Основна снимка", name: "image", widget: "image" }
      - { label: "Кратко описание", name: "excerpt", widget: "text" }
      - { label: "Текст на статията", name: "body", widget: "markdown" }
