backend:
  name: github
  repo: MarianaKlimentieva/Spisanieto
  branch: main
  base_url: https://decap-server.herokuapp.com

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Статии"
    folder: "_posts"
    create: true
    fields:
      - {label: "Заглавие", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Съдържание", name: "body", widget: "markdown"}
